# Generated by Django 2.2 on 2020-04-09 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user_id', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '09128158817'. Up to 15 digits allowed.", regex='^\\09?\\d{11,11}$')])),
                ('email', models.CharField(max_length=150, unique=True, validators=[django.core.validators.EmailValidator])),
                ('address', models.TextField()),
                ('purchase', models.CharField(max_length=150)),
                ('purchase_id', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('blog_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
