# Generated by Django 2.2 on 2020-04-09 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20200409_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.CharField(max_length=150, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
