# Generated by Django 2.2 on 2020-04-09 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_auto_20200409_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='(0|\\+98)?([ ]|,|-|[()]){0,2}9[1|2|3|4]([ ]|,|-|[()]){0,2}(?:[0-9]([ ]|,|-|[()]){0,2}){8}')]),
        ),
    ]
