# Generated by Django 2.2 on 2020-04-09 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20200409_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^09[0|1|2|3][0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='purchase_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
