# Generated by Django 2.2 on 2020-04-10 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_auto_20200409_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='purchase_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
